spring.application.name=bliblioteca
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:56155/railway?allowPublicKeyRetrieval=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=hTfKiJSbQFlPQwrllILvHeEkamFCPngd
spring.security.user.name=admin
spring.security.user.password=MiClaveSegura123!
spring.security.user.roles=ADMIN
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=osWXaFeA/Fk7enuKkF4dlyU0Wv2MMx0RK/9pCjvX27YYsn4CAbUvHNh5Dpnv6mXNn5WyIXPxw/IQj8EwmHRp7A==
jwt.expiration=3600000
server.port=${PORT:8080}

